### PR TITLE
Complete translation and update formatting

### LINKED ISSUE #16: translate non-episode files
The following files need translations before publication:

- [x] [setup.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/setup.md)
- [x] [index.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/index.md)

The following files can be translated later (after publication): 

- [x] [reference.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/reference.md)
- [x] [README.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/README.md)
- [x] [_extras/discuss.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/_extras/discuss.md)
- [x] [_extras/guide.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/_extras/guide.md)

The following files need translations, but I think these files come in from styles: 
- [x] [LICENSE.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/LICENSE.md)
- [x] [CONTRIBUTING.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/CONTRIBUTING.md)
- [x] [CONDUCT.md](https://github.com/Carpentries-ES/shell-novice/blob/gh-pages/CONDUCT.md)

### PR DESCRIPTION
**Pull request by ErinBecker**
This PR fixes https://github.com/Carpentries-ES/shell-novice/issues/16 and https://github.com/Carpentries-ES/shell-novice/issues/15.

It also:
- Translates all template files (through https://github.com/erinbecker/styles-es)
- Fixes formatting of challenges

@orchid00

### CODE REVIEW

**Comment by ErinBecker** [comment]
The error message says that _episodes_es/index.md and _episodes_es/setup.md have merge conflicts, but these files are no longer required, as everything has been moved to _episodes following technical guidance from @rgaiacs.

**Comment by ErinBecker** [comment]
@orchid00 - I wonder if the easiest thing to do, rather than trying to merge this PR, is to transfer ownership of the clean repo from https://github.com/ErinBecker/shell-novice-es to https://github.com/swcarpentry/shell-novice-es. I forked from https://github.com/Carpentries-ES/shell-novice, so all of the contribution history should be preserved.

**Comment by orchid00** [comment]
👏🏽👏🏽👏🏽👏🏽👏🏽 :D I am so happy to see this progressing! Thank you @ErinBecker @rgaiacs 
Also, I can see the names of translators on contributors! and that's great!

Question. where are the extra files?


A few points I cached, please let me know If I should open these as issues
Should I translate this: https://github.com/ErinBecker/shell-novice-es/blob/gh-pages/CONTRIBUTING.md

Maybe we need to update and translate this: should say cita instead of cite
https://github.com/ErinBecker/shell-novice-es/blob/gh-pages/CITATION

in "Contacto"
should it me mailto:lessons@software-carpentry.org
instead of
https://erinbecker.github.io/shell-novice-es/lessons@software-carpentry.org

**Comment by ErinBecker** [comment]
Thanks @orchid00! Glad to see you're enthusiastic!

To answer your questions:

- The extra files are in _extras/ (which is where they are in the English lessons as well). With this strategy, we don't need to change the repo organization to accommodate the Spanish and English files in the same repo. 

- CONTRIBUTING.md - Yes please! I missed this file. If you could do a translation it would be great. 

- CITATION - from my understanding, the citation shouldn't be changed until the next lesson release, as we're citing an official version of the lessons (published on zenodo). We can publish these lessons when they're ready (almost there!) and update this citation at that point. We will also need to update the Maintainers list to reflect the Maintainers for the Spanish version of this lesson.

- Contacto is coming from _includes/workshop_footer.html which includes the line 

>> `<a href="mailto:{{ site.email }}">Contacto</a>`

This is pulling from _config.yml from the line

>> `email: lessons@software-carpentry.org`

I'm not sure why it's pointing towards https://erinbecker.github.io/shell-novice-es/lessons@software-carpentry.org instead of lessons@software-carpentry.org. Maybe @rgaiacs can clarify why the template is set up this way?

**Comment by ErinBecker** [comment]
I'm about to put in a PR for the git lesson!

**Comment by ErinBecker** [comment]
@orchid00 - I got excited and did a translation of CONTRIBUTING.md. Can you please look it over and let me know how it looks? If things here generally look ok, I propose that we transfer ownership of this over to the swcarpentry organization and do a final clean up there before publishing.

**Comment by orchid00** [comment]
@ErinBecker I will check now

**Comment by orchid00** [comment]
@ErinBecker cool translation! I've changed slightly a few wordings

**Comment by orchid00** [comment]
@ErinBecker I just noticed that come links in the CONTRIBUTING are not going to the right place

**Comment by rgaiacs** [comment]
> I'm not sure why it's pointing towards https://erinbecker.github.io/shell-novice-es/lessons@software-carpentry.org instead of lessons@software-carpentry.org. Maybe @rgaiacs can clarify why the template is set up this way?

Please see https://github.com/swcarpentry/styles/pull/206. A pull request should worth a thousand words. :-)

**Comment by orchid00** [comment]
@ErinBecker I was unable to merge this because I'm not sure how to handle the conflict. 
It might be because of repetitive files index and setup. you can delete them.
I added you as contributor so you are able to change the files

**Comment by orchid00** [comment]
hi @fmichonneau now you also have writing permissions maybe you can help us fixing this git "conflict" thanks

**Comment by ErinBecker** [comment]
Thanks Paula and Francois for getting the merge conflict sorted out!

**Pull request merged**
